services:
  pfu:
    image: pfu:latest
    # Change these to non-root UID and GID of your choosing. There's no need to run both these containers as root.
    user: 1000:1000
    environment:
      # Make sure to change these to actual secure values; note the double $ characters in PFU_AUTH_SECRET variable
      - "PFU_SECRET_KEY=secret"
      - "PFU_AUTH_SECRET=pbkdf2:sha256:260000$$HGnxHKS9Ffbe8K3l$$e003b7963e4cf49d4e075087a55e90c85345754306a35fc2d9c571c31f19c393"
    volumes:
      - "/home/user/docker/pfu/uploads:/uploads"
      - "/home/user/docker/pfu/data:/data"
    # Add uploader container to traefik's network
    networks:
      - proxy
    # Example traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pfu.rule=Host(`upload.example.dev`)"
      - "traefik.http.routers.pfu.entrypoints=websecure"
      - "traefik.http.routers.pfu.tls.certresolver=letsencrypt"
  sws:
    image: joseluisq/static-web-server:2
    # See above
    user: 1000:1000
    environment:
      - SERVER_LOG_LEVEL=info
    volumes:
      - "/home/user/docker/pfu/uploads:/public"
    # Add file serving container to traefil's network
    networks:
      - proxy
    # These traefik labels allow you to serve files at the same domain from a subdirectory
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sws.rule=(Host(`upload.example.dev`) && PathPrefix(`/files/`))"
      - "traefik.http.middlewares.sws-stripprefix.stripprefix.prefixes=/files"
      - "traefik.http.routers.sws.middlewares=sws-stripprefix"
      - "traefik.http.routers.sws.entrypoints=websecure"
      - "traefik.http.routers.sws.tls.certresolver=letsencrypt"

# Specify that traefik's network is external to this compose file
networks:
  proxy:
    external: true
