[project]
name = "pfu"
version = "1.0.1"
description = "Python file uploader using Flask"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bootstrap-flask>=2.5.0",
    "colorlog>=6.10.1",
    "flask>=3.1.2",
    "flask-apscheduler>=1.13.1",
    "flask-login>=0.6.3",
    "peewee>=3.18.3",
    "types-peewee>=4.0.0.20260223",
    "waitress>=3.0.2",
    "werkzeug>=3.1.4",
]

[[tool.mypy.overrides]]
module = [
    "flask_login",
    "flask_login.*",
    "flask_apscheduler",
    "flask_apscheduler.*",
    "flask_bootstrap",
    "flask_bootstrap.*",
]
ignore_missing_imports = true
